before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - format: binary
checksum:
  disable: true
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^todo:"
      - "typo"
