before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X github.com/kkga/tdx/cmd.AppVersion={{.Version}}

archives:
  - format: binary

checksum:
  disable: true

snapshot:
  name_template: '{{ incpatch .Version }}-next'

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^todo'
      - '^wip'
      - 'minor'
      - 'WIP'
      - 'typo'
      - Merge pull request
      - Merge branch
      - go mod tidy
