tdx
===

link::https://hitsofcode.com/github/kkga/tdx?branch=main/view[image::https://hitsofcode.com/github/kkga/tdx?branch=main)][Hits-of-Code]]

:iCalendar: https://en.wikipedia.org/wiki/ICalendar[iCalendar]
:vdirsyncer: https://github.com/pimutils/vdirsyncer[Vdirsyncer]
:vdirstorage: https://vdirsyncer.pimutils.org/en/latest/vdir.html[storage format]
:vdirdocs: https://vdirsyncer.pimutils.org/en/stable/index.html[Vdirsyncer documentation]

`tdx` is a todo manager for {iCalendar} files.

It is designed to work with {vdirsyncer} and expects to operate in its
{vdirstorage}.

iCalendar-compatibility means it can be used as a CLI companion to any
CalDAV-enabled todo program, such as iOS Reminders. See more on how to set up
calendars and synchronization in {vdirdocs}.


Features
--------

* adding todos
** automatic date and priority parsing
* listing todos
** sorting and filtering by fields
** automatic hashtag parsing and output organized by tags
* completing todos
* editing todos in a `$VISUAL`/`$EDITOR` program
* deleting todos
* purging completed/cancelled todos

Demo
----

.Quick demo of basic interactions
https://user-images.githubusercontent.com/1460122/135115870-b0236b4a-aa53-45f9-b534-111d2e4849a8.mp4

Usage
-----

.General usage
-------------------------------------------------------------------------------
> tdx -h
tdx -- todo manager for vdir (iCalendar) files
Gadzhi Kharkharov <x@kkga.me>

USAGE
  tdx <command> [options] [<args>...]

  list, ls       list todos
COMMANDS
  add, a         add todo
  done, do       complete todos
  edit, e        edit todo
  delete, del    delete todos
  purge          remove completed todos
  show           show todo info

  See 'tdx <command> -h' for command usage

ENVIRONMENT VARIABLES
  TDX_PATH (required)
        path to vdir directory;
        either root vdir directory with multiple collections
        or direct path to a single collection.
  TDX_LIST_OPTS
        default options for <list> command, see 'tdx list -h';
        example: filter by due date in next 2 days, from 'myList', organized by tags...
            TDX_LIST_OPTS='-d=2 -l=myList -t'
  TDX_ADD_OPTS
        default options for <add> command, see 'tdx add -h';
        example: use a default list for new todos...
            TDX_ADD_OPTS='-l=myList'
  NO_COLOR
        disable colors in output

FLAGS
  -v    print version
  -h    print help
-------------------------------------------------------------------------------


.Adding todos
-------------------------------------------------------------------------------
> tdx add -h
Add new todo

USAGE
  tdx add [options] <todo>

OPTIONS
  -d description
        description text
  -l list
        list for new todo

AUTOMATIC PROPERTY PARSING
  due date
        If todo text contains a date in any of the following
        forms, it will be converted to due date:
        - "today", "tomorrow", "next tuesday"
        - "in 3 days", "in a few days", "in 2 weeks", "in a month"
        - "december 1st", "15 nov", "jul"
  priority
        If todo text contains one or more "!" chars,
        they will be converted to priority:
        - "!!!" (high)
        - "!!"  (medium)
        - "!"   (low)

ENVIRONMENT VARIABLES
  TDX_ADD_OPTS
        default options for <add> command;
        example: use a default list for new todos...
            TDX_ADD_OPTS='-l=myList'
-------------------------------------------------------------------------------

Configuration
-------------

`tdx` is configured through environment variables.

*TDX_PATH* (required)::
    path to http://vdirsyncer.pimutils.org/en/stable/vdir.html[vdir directory]; +
    either root path containing multiple collections or path to specific
    collection containing _*.ics_ files
*TDX_LIST_OPTS*::
    default options for *<list>* command, see `tdx list -h`; +
    example: show todos due in the next 2 days, from 'myList', organized by tags... +
        `TDX_LIST_OPTS='-d=2 -l=myList -t'``
*TDX_ADD_OPTS*::
    default options for *<add>* command, see `tdx add -h`; +
    example: use a default list for new todos... +
        `TDX_ADD_OPTS='-l=myList'`
*NO_COLOR*::
    disables color in output

Installation
------------

From release binaries
~~~~~~~~~~~~~~~~~~~~~

Download the compiled binary for your system from
https://github.com/kkga/tdx/releases[Releases] page and put it somewhere
in your `$PATH`.

From source
~~~~~~~~~~~

Requires https://golang.org/[Go] installed on your system.

Clone the repository and run `go build`, then copy the compiled binary
somewhere in your `$PATH`.

If Go is https://golang.org/ref/mod#go-install[configured] to install
packages in `$PATH`, it's also possible to install without cloning the
repository:

----
go install github.com/kkga/tdx@latest
----
