tdx
===

:iCalendar: https://en.wikipedia.org/wiki/ICalendar[iCalendar]
:vdirsyncer: https://github.com/pimutils/vdirsyncer[Vdirsyncer]
:vdirstorage: https://vdirsyncer.pimutils.org/en/latest/vdir.html[storage format]
:vdirdocs: https://vdirsyncer.pimutils.org/en/stable/index.html[Vdirsyncer documentation]

`tdx` is a todo manager for {iCalendar} files.

It is designed to work with {vdirsyncer} and expects to operate in its
{vdirstorage}.

iCalendar-compatibility means it can be used as a CLI companion to any
CalDAV-enabled todo program, such as iOS Reminders. See more on how to set up
calendars and synchronization in {vdirdocs}.


Features
--------

* adding todos with automatic date and priority parsing;
* listing todos, with sorting and filtering options;
* completing todos;
* editing todos in a `$VISUAL`/`$EDITOR` program;
* deleting todos;
* purging completed/cancelled todos.

Demo
----

.Quick demo of basic interactions
https://user-images.githubusercontent.com/1460122/135115870-b0236b4a-aa53-45f9-b534-111d2e4849a8.mp4

Usage
-----

.General usage
-------------------------------------------------------------------------------
> tdx -h
tdx -- todo manager for vdir (iCalendar) files
Gadzhi Kharkharov <x@kkga.me>

USAGE
  tdx <command> [options] [<args>...]

COMMANDS
  list, ls       list todos
  add, a         add todo
  done, do       complete todos
  edit, e        edit todo
  delete, del    delete todos
  purge          remove completed todos
  show           show todo info

  See 'tdx <command> -h' for command usage

ENVIRONMENT VARIABLES
  TDX_PATH              path to vdir directory (required)
  TDX_DEFAULT_LIST      list to use for <list>, <add> commands
  TDX_DEFAULT_STATUS    status filter for <list> command, see 'tdx list -h'
  TDX_DEFAULT_SORT      sorting order for <list> command, see 'tdx list -h'
  NO_COLOR              disable colors in output

FLAGS
  -v    print version
  -h    print help
-------------------------------------------------------------------------------


.Adding todos
-------------------------------------------------------------------------------
> tdx add -h
Add new todo

USAGE
  tdx add [options] <todo>

DUE DATE
  If todo text contains a date in one of the following
  formats, it will be applied as due date:
  * "today", "tomorrow", "in 3 days", "in 2 weeks"
  * "next week", "next month", "next monday"
  * ordinal date: "december 1st", "15th november"

PRIORITY
  If todo text contains one or more "!" chars,
  they will be converted to priority:
  * "!!!" (high)
  * "!!"  (medium)
  * "!"   (low)

OPTIONS
  -d description
        description text
  -l list
        list for new todo
-------------------------------------------------------------------------------

Configuration
-------------

`tdx` is configured through environment variables.

*TDX_PATH* (required)::
    `<path>` +
    path to http://vdirsyncer.pimutils.org/en/stable/vdir.html[vdir directory]; +
    either root path containing multiple collections or path to specific
    collection containing _*.ics_ files
*TDX_DEFAULT_LIST*::
    `<list name>` +
    list to use for *list* and *add* commands; +
    can be overridden with `-l` flag
*TDX_DEFAULT_STATUS*::
    `NEEDS-ACTION|COMPLETED|CANCELLED|ANY` +
    default: `NEEDS-ACTION` +
    status filter for *list* command; +
    can be overridden with `-S` flag
*TDX_DEFAULT_SORT*::
    `PRIO|DUE|STATUS|CREATED` +
    default: `PRIO` +
    sorting option for *list* command; +
    can be overridden with `-s` flag
*NO_COLOR*::
    `<any>` +
    disables color in output

Installation
------------

From release binaries
~~~~~~~~~~~~~~~~~~~~~

Download the compiled binary for your system from
https://github.com/kkga/tdx/releases[Releases] page and put it somewhere
in your `$PATH`.

From source
~~~~~~~~~~~

Requires https://golang.org/[Go] installed on your system.

Clone the repository and run `go build`, then copy the compiled binary
somewhere in your `$PATH`.

If Go is https://golang.org/ref/mod#go-install[configured] to install
packages in `$PATH`, it's also possible to install without cloning the
repository:

----
go install github.com/kkga/tdx@latest
----
